name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # Tous les jours à minuit
  workflow_dispatch:    # Permet de lancer manuellement

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync upstream changes
        run: |
          git remote add upstream https://github.com/PokeAPI/sprites.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          git push origin master
